### ISSUE TITLE
Result for case 'f'?

### ISSUE THREAD

**Issue by WadeJA** [yryz/ds18b20#1]
With all due respect, while I agree (FWIW) with the code in case '0', I question case 'f'. 
To try to help, the 2 hex strings (data) I get back from 2 DSs are: 
dd ff 4b 46 7f ff 03 10 25 : crc=25 YES
16 00 4b 46 7f ff 0a 10 a5 : crc=a5 YES
The temp is hovering around 0C and have used several DSs, all of which provide reasonably accurate results once the temps rise above about .5 thru 1.5C (w/in variances and compared against other HTU21D and AM2315 probes, as well as WeatherUnderground).

**Comment by yryz** [comment]
dd ff 4b 46 7f ff 03 10 25 : crc=25 YES
What's the real temperature? Can you give me the second line of data?
